### ISSUE TITLE
It seems the EXTENSIONS is no  Kendryte plugin？

### ISSUE THREAD

**Issue by ghost** [kendryte/Kendryte-dev-extension#1]
![ken](https://user-images.githubusercontent.com/30285313/70194473-7d3fd280-173d-11ea-8dd2-3ff01610d232.png)
![ken1](https://user-images.githubusercontent.com/30285313/70194476-7fa22c80-173d-11ea-845a-9c864213453f.png)

**Comment by Raylin51** [comment]
We have not released the preview version yet. The extension is on final round of testing now. You can find it on extension market next week. Thank you for your attention.

**Comment by ghost** [comment]
got it
