### ISSUE TITLE
Upload fail on KD233

### ISSUE THREAD

**Issue by mangobuge** [kendryte/Kendryte-dev-extension#2]
Tested on KD233/AIRV/DAN, after Build and Upload button,Output give "Upload finished", but it is not actually uploaded.
I haven't seen the board move, I suspect that kflash.py is not actually called.

**Comment by Raylin51** [comment]
Can you post the log of upload? The log is on upload output channel.

**Comment by MangoNoFlake** [comment]
[errorlog.mp4](https://sns.widora.io/assets/uploads/files/1581141084270-main.c-camera-screen-standalone-visual-studio-code-2020-02-08-13-49-19.mp4)

**Comment by Raylin51** [comment]
It seems like kflash.py is not called. Can you open VSCode's developer tools and post the error log on console?

**Comment by MangoNoFlake** [comment]
only one error: 
 [Extension Host] 子进程退出，退出码 3221225781 workbench.desktop.main.js:sourcemap:259 
 
sometime show this error:  
子进程退出，退出码 3221225781   console.ts:137 

locate : Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js

**Comment by Raylin51** [comment]
I will check it these days. You will get notice when this bug fixed.

**Comment by Raylin51** [comment]
Due to the absence of `python34.dll`, `kflash.py` will not execute normally. You can install [Python 3.4.4](https://www.python.org/downloads/release/python-344/) to fix it temporary. We are rewriting kflash module  on typescript to prevent some question on windows. Closed.
